import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
const apiUrl = (process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000/api/v1').replace(/\/+$/, '');
const authMeUrl = /\/api\/v1$/i.test(apiUrl) ? `${apiUrl}/auth/me` : `${apiUrl}/api/v1/auth/me`;

async function getUser(req: NextRequest) {
  const token = req.cookies.get('es_auth_token')?.value;
  if (!token) return null;
  const res = await fetch(authMeUrl, { headers: { Authorization: `Bearer ${token}` }, cache: 'no-store' });
  if (!res.ok) return null;
  const json = await res.json();
  return json?.data ?? null;
}

export async function POST(req: NextRequest) {
  try {
    const user = await getUser(req);
    if (!user?.id) return NextResponse.json({ success: false, error: { message: 'Unauthorized' } }, { status: 401 });
    const body = await req.json();
    const items = Array.isArray(body.items) ? body.items : [];
    if (!items.length || !body.address_id || !body.courier) {
      return NextResponse.json({ success: false, error: { message: 'Data checkout tidak lengkap' } }, { status: 400 });
    }

    const { data: address } = await supabase.from('buyer_addresses').select('*').eq('id', body.address_id).eq('buyer_id', user.id).single();
    if (!address) return NextResponse.json({ success: false, error: { message: 'Alamat tidak valid' } }, { status: 400 });

    const subtotal = items.reduce((acc: number, it: any) => acc + Number(it.subtotal || 0), 0);
    const deliveryFee = Number(body.delivery_fee ?? 0);
    const discount = Number(body.discount_amount ?? 0);
    const totalAmount = subtotal + deliveryFee - discount;

    // Ambil semua farmer_id (Profile ID) unik dari items
    const farmerProfileIds = [...new Set(items.map((it: any) => it.farmer_id))].filter(Boolean);
    
    // Cari mapping Profile ID -> User ID
    const { data: profiles } = await supabase
      .from('farmer_profiles')
      .select('id, user_id')
      .in('id', farmerProfileIds);

    const profileToUserMap = (profiles ?? []).reduce((acc: any, p: any) => {
      acc[p.id] = p.user_id;
      return acc;
    }, {});

    const firstFarmerProfileId = items[0]?.farmer_id;

    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert({
        order_number: '', // Will be generated by trigger
        buyer_id: user.id,
        farmer_id: firstFarmerProfileId, // Keep storing Profile ID in orders for the detail API join logic (already fixed above)
        buyer_name: body.buyer_name ?? user.name ?? 'Pembeli',
        buyer_phone: body.buyer_phone ?? user.phone ?? '-',
        buyer_email: body.buyer_email ?? user.email ?? '-',
        shipping_name: address.recipient_name,
        shipping_phone: address.phone,
        shipping_province: address.province,
        shipping_city: address.city,
        shipping_district: address.district,
        shipping_address: address.address,
        shipping_postal: address.postal_code ?? null,
        shipping_notes: body.shipping_notes ?? null,
        courier: body.courier,
        delivery_type: body.delivery_type ?? 'reguler',
        delivery_fee: deliveryFee,
        estimated_days: body.estimated_days ?? '3-5 hari kerja',
        subtotal,
        discount_amount: discount,
        promo_code: body.promo_code ?? null,
        total_amount: totalAmount,
        payment_method: body.payment_method ?? 'transfer_bank',
        payment_bank: body.payment_bank ?? null,
        payment_status: 'pending',
        payment_deadline: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
        status: 'menunggu_pembayaran',
        notes: body.notes ?? null,
      })
      .select('*')
      .single();

    if (orderError || !order) {
      console.error('Order creation failed:', orderError);
      return NextResponse.json({ success: false, error: { message: orderError?.message ?? 'Gagal membuat order' } }, { status: 500 });
    }

    const itemRows = items.map((it: any) => ({
      order_id: order.id,
      product_id: it.product_id,
      // Use User ID for order_items as per the migration (references public.users)
      farmer_id: profileToUserMap[it.farmer_id] || it.farmer_id,
      farmer_name: it.farmer_name ?? '-',
      farmer_avatar: it.farmer_avatar ?? '🌾',
      farmer_city: it.farmer_city ?? '-',
      product_name: it.product_name,
      product_emoji: it.product_emoji ?? '📦',
      unit: it.unit ?? 'kg',
      qty: Number(it.qty ?? 1),
      price_per_unit: Number(it.price_per_unit ?? 0),
      subtotal: Number(it.subtotal ?? 0),
      is_wholesale: Boolean(it.is_wholesale ?? false),
      notes: it.notes ?? null,
    }));
    
    const { error: itemsError } = await supabase.from('order_items').insert(itemRows);
    if (itemsError) {
      console.error('Error inserting order items:', itemsError);
      // We don't necessarily want to fail the whole request if order is already created,
      // but in a real app we would use a transaction.
    }

    return NextResponse.json({ success: true, data: { order_id: order.id, order_number: order.order_number } });
  } catch (error) {
    return NextResponse.json({ success: false, error: { message: error instanceof Error ? error.message : 'Terjadi kesalahan' } }, { status: 500 });
  }
}
